# Generated by Django 4.1.1 on 2022-10-04 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condition1', '0003_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='emal',
            new_name='email',
        ),
        migrations.AddField(
            model_name='comment',
            name='body',
            field=models.TextField(default='test@wp.pl'),
            preserve_default=False,
        ),
    ]
